# 크롬 드라이버 설정

## 크롬 드라이버 설정

In [ ]:
# -*- coding: utf-8 -*-

In [ ]:
import sys
print(sys.getdefaultencoding())

utf-8

In [ ]:
#ubuntu 업데이트
# !apt-get update

#셀레늄 패키지 다운
# !pip install selenium

#크롬드라이버 다운
# !apt install chromium-chromedriver
# !cp /usr/lib/chromium-browser/chromedriver /usr/bin

#크롬드라이버 경로 설정
import sys
sys.path.insert(0, '/usr/lib/chromium-browser/chromedriver')

#코랩에서 작동하도록 옵션 설정
from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_argument('-headless')
options.add_argument('-no-sandbox')
options.add_argument('-disable-dev-shm-usage')

## Beautiful Soup 로딩

In [ ]:
#정보요청 라이브러리 import
import requests

#크롤링 라이브러리 import
from bs4 import BeautifulSoup

C:\Users\rlagk\anaconda3\lib\site-packages\requests\__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

## Selenium 로딩

In [ ]:
#셀레늄 라이브러리 불러오기
from selenium import webdriver

#셀레늄에서 html문서가 생성될 때까지 대기하는 함수 불러오기
from selenium.webdriver.support.ui import WebDriverWait

#셀레늄에서 조건을 걸어줄 수 있는 함수 불러오기
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

## User agent  설정

In [ ]:
#User-Agent 지정
headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36'}

## 필요 Library 로딩

In [ ]:
import pandas as pd
import numpy as np

# 모바일 인덱스 크롤링

In [ ]:
#크롤링 할 대상 url 지정
url = 'https://www.mobileindex.com/home?pkg=com.sleepmonitor.aio&route=app-detail%2Fusage-info%2Fusage-analysis'

#크롤링 대상 url과 headers를 기반으로 정보 요청
res = requests.get(url, headers = headers)

#정상적으로 정보를 받은 경우 지속, 그렇지 않은 경우 중지
res.raise_for_status()

#html문서를 beautifulsoup의 lxml 형태로 변환
soup = BeautifulSoup(res.text, 'lxml')

## 슬립 모니터 크롤링

In [ ]:
#드라이버 객체 생성
# 절대 경로로 지정해 줘서 경로 지정 오류 해결 
# 크롤링하면서 모니터링 할 브라우저 오픈 
browser = webdriver.Chrome(executable_path = 'C:/chromedriver_win32/chromedriver.exe')

<ipython-input-9-a8d93f155573>:4: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(executable_path = 'C:/chromedriver_win32/chromedriver.exe')

### 기본 사용량

#### 사용자 수

In [ ]:
#모바일인덱스 슬립모니터 사이트 기본 사용량 분석으로 접속
browser.get('https://www.mobileindex.com/home?pkg=com.sleepmonitor.aio&route=app-detail%2Fapp-info%2Fsummary')
browser.implicitly_wait(time_to_wait=4)

In [ ]:
browser.find_element_by_xpath('//*[@id="root"]/article/div/div[1]/section').click()
browser.find_element_by_xpath('//*[@id="root"]/article/div/div[1]/section/div/button').click()

<ipython-input-11-342cdd033875>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="root"]/article/div/div[1]/section').click()
<ipython-input-11-342cdd033875>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="root"]/article/div/div[1]/section/div/button').click()

In [ ]:
ID ='ID입력'
PW =  'PW입력'

In [ ]:
#ID 입력
browser.find_element_by_xpath('//*[@id="page-scroll-obj"]/section/article/section/div[1]/span/span/span[2]/input').send_keys(ID)
browser.implicitly_wait(time_to_wait=5)

# PW 입력
browser.find_element_by_xpath('//*[@id="page-scroll-obj"]/section/article/section/div[2]/span/span/span[2]/input').send_keys(PW)
browser.implicitly_wait(time_to_wait=5)

# 로그인 클릭 
browser.find_element_by_xpath('//*[@id="page-scroll-obj"]/section/article/section/span[1]/span').click()
browser.implicitly_wait(time_to_wait=5)

<ipython-input-13-698e33ed8033>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-scroll-obj"]/section/article/section/div[1]/span/span/span[2]/input').send_keys(ID)
<ipython-input-13-698e33ed8033>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-scroll-obj"]/section/article/section/div[2]/span/span/span[2]/input').send_keys(PW)
<ipython-input-13-698e33ed8033>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-scroll-obj"]/section/article/section/span[1]/span').click()

In [ ]:
#모바일인덱스 슬립모니터 사이트 기본 사용량 분석으로 접속
browser.get('https://www.mobileindex.com/home?pkg=com.sleepmonitor.aio&route=app-detail%2Fapp-info%2Fsummary')
browser.implicitly_wait(time_to_wait=4)

In [ ]:
#기본 사용량 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[2]').click()
browser.implicitly_wait(time_to_wait=5)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

<ipython-input-15-d145b03918e0>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[2]').click()
<ipython-input-15-d145b03918e0>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-15-d145b03918e0>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

In [ ]:
# 기간 선택
# browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[2]/div/div[2]/span').click()
# browser.implicitly_wait(time_to_wait=3)

In [ ]:
# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 범위 생성 
range = np.arange(184)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])


# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date','And'])

# df csv로 저장
df.to_csv('C:/R/슬립모니터_기본사용량_사용자_수.csv',index=True)

# df 확인 
df

          date      And
0   2021-10-20  2,151 명
1   2021-10-21  2,079 명
2   2021-10-22  1,965 명
3   2021-10-23  1,654 명
4   2021-10-24  1,839 명
..         ...      ...
87  2022-01-15  1,888 명
88  2022-01-16  2,154 명
89  2022-01-17  2,450 명
90  2022-01-18  2,340 명
91  2022-01-19  2,289 명

[92 rows x 2 columns]

#### 사용 시간

In [ ]:
#사용 시간 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

<ipython-input-18-1c6bc88bb72f>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

In [ ]:
# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 범위 생성 
range = np.arange(274)

# 공란 리스트 생성 
date = []
Total_time = []
Personal_average_time = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 3 == 0:
        date.append(notice_list[i])
    elif i % 3 == 1: 
        Total_time.append(notice_list[i])
    elif i % 3 == 2: 
        Personal_average_time.append(notice_list[i])

        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, Total_time, Personal_average_time]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'Total_time', 'Personal_average_time'])

# df csv로 저장
df.to_csv('C:/R/슬립모니터_기본사용량_사용_시간.csv',index=True)


# df 확인 
df

          date Total_time Personal_average_time
0   2021-10-20     149 시간                4.15 분
1   2021-10-21     138 시간                4.00 분
2   2021-10-22     197 시간                6.02 분
3   2021-10-23     181 시간                6.58 분
4   2021-10-24     329 시간               10.73 분
..         ...        ...                   ...
87  2022-01-15     130 시간                4.13 분
88  2022-01-16     254 시간                7.07 분
89  2022-01-17     256 시간                6.27 분
90  2022-01-18     264 시간                6.78 분
91  2022-01-19       None                  None

[92 rows x 3 columns]

#### 활성 기기

In [ ]:
# 활성 기기 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[3]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)
    
# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(12)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date','And'])

# df csv로 저장
df.to_csv('C:/R/슬립모니터_기본사용량_활성기기.csv',index=True)

# df 확인 
df

<ipython-input-22-e9c52da7e531>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[3]').click()

      date       And
0  2021-07  29,444 대
1  2021-08  28,952 대
2  2021-09  29,780 대
3  2021-10  30,024 대
4  2021-11  31,080 대
5  2021-12  31,828 대

#### 신규 설치 건 수

In [ ]:
# 신규 설치 건 수 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[4]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

#대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(184)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])

        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And'])

# df csv로 저장
df.to_csv('C:/R/슬립모니터_기본사용량_신규_설치건수.csv',index=True)

# df 확인 
df

<ipython-input-24-ee3aa68991b3>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[4]').click()

          date    And
0   2021-10-20   69 건
1   2021-10-21   90 건
2   2021-10-22  107 건
3   2021-10-23   78 건
4   2021-10-24   59 건
..         ...    ...
87  2022-01-15  158 건
88  2022-01-16  215 건
89  2022-01-17  232 건
90  2022-01-18  131 건
91  2022-01-19  148 건

[92 rows x 2 columns]

### 데모그래픽

#### 사용자 구성

In [ ]:
#데모그래픽 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[3]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

<ipython-input-25-6a23532a7a4f>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[3]').click()
<ipython-input-25-6a23532a7a4f>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-25-6a23532a7a4f>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

In [ ]:
# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 범위 생성 
range = np.arange(35)

# 공란 리스트 생성 
Start = []
End = []
Age = []
Male = []
Female = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 5 == 0:
        Start.append(notice_list[i])    
    elif i % 5 == 1: 
        End.append(notice_list[i])
    elif i % 5 == 2: 
        Age.append(notice_list[i])
    elif i % 5 == 3: 
        Male.append(notice_list[i])    
    elif i % 5 == 4: 
        Female.append(notice_list[i])    
        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([Start, End, Age, Male, Female]).transpose()

# 칼럼명 변경 
df.columns = (['Start', 'End', 'Age', 'Male', 'Female'])

# df csv로 저장
df.to_csv('C:/R/슬립모니터_데모그래픽_사용자구성.csv',index=True)

# df 확인 
df

        Start         End     Age     Male   Female
0  2021-10-20  2022-01-19      전체  34.66 %  65.34 %
1  2021-10-20  2022-01-19  10대 이하   3.74 %   8.40 %
2  2021-10-20  2022-01-19     20대  12.76 %  29.46 %
3  2021-10-20  2022-01-19     30대   8.08 %  12.31 %
4  2021-10-20  2022-01-19     40대   5.53 %   9.00 %
5  2021-10-20  2022-01-19     50대   3.96 %   4.49 %
6  2021-10-20  2022-01-19  60대 이상   0.59 %   1.68 %

#### 연령별 사용시간 구성

In [ ]:
# 연령별 사용시간 구성 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 범위 생성 
range = np.arange(35)

# 공란 리스트 생성 
Start = []
End = []
Age = []
Male = []
Female = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 5 == 0:
        Start.append(notice_list[i])    
    elif i % 5 == 1: 
        End.append(notice_list[i])
    elif i % 5 == 2: 
        Age.append(notice_list[i])
    elif i % 5 == 3: 
        Male.append(notice_list[i])    
    elif i % 5 == 4: 
        Female.append(notice_list[i])    
        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([Start, End, Age, Male, Female]).transpose()

# 칼럼명 변경 
df.columns = (['Start', 'End', 'Age', 'Male', 'Female'])

# df csv로 저장
df.to_csv('C:/R/슬립모니터_데모그래픽_사용자구성.csv',index=True)

# df 확인 
df

<ipython-input-28-da54f32a3f35>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

        Start         End     Age     Male   Female
0  2021-10-20  2022-01-19      전체  33.45 %  62.81 %
1  2021-10-20  2022-01-19  10대 이하   3.74 %  10.51 %
2  2021-10-20  2022-01-19     20대  12.69 %  24.89 %
3  2021-10-20  2022-01-19     30대   8.32 %  10.41 %
4  2021-10-20  2022-01-19     40대   6.90 %  11.43 %
5  2021-10-20  2022-01-19     50대   2.85 %   3.53 %
6  2021-10-20  2022-01-19  60대 이상   2.69 %   2.04 %

### 순위 히스토리

#### 사용자 순위

In [ ]:
#순위 히스토리 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[4]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span').click()
browser.implicitly_wait(time_to_wait=4)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

<ipython-input-29-a6844a5bc697>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[4]').click()
<ipython-input-29-a6844a5bc697>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span').click()
<ipython-input-29-a6844a5bc697>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span/span/span[2]').click()

In [ ]:
# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 범위 생성 
range = np.arange(368)

# 공란 리스트 생성 
date = []
Total = []
And = []
IOS = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        Total.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])
        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, Total, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'Total', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/슬립모니터_순위히스토리_사용자 순위.csv',index=True)

# df 확인 
df

          date   Total    And     IOS
0   2021-10-20  null 위  147 위  null 위
1   2021-10-21  null 위  149 위  null 위
2   2021-10-22  null 위  220 위  null 위
3   2021-10-23  null 위  202 위  null 위
4   2021-10-24  null 위  199 위  null 위
..         ...     ...    ...     ...
87  2022-01-15  null 위  267 위  null 위
88  2022-01-16  null 위  110 위  null 위
89  2022-01-17  null 위  139 위  null 위
90  2022-01-18  null 위  182 위  null 위
91  2022-01-19  null 위  138 위  null 위

[92 rows x 4 columns]

#### 사용시간 순위

In [ ]:
# 사용시간 순위 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 범위 생성 
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/슬립모니터_순위히스토리_사용시간순위.csv',index=True)

# df 확인 
df

<ipython-input-32-e09e20e62190>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

          date And_IOS    And     IOS
0   2021-10-20  null 위  322 위  null 위
1   2021-10-21  null 위  318 위  null 위
2   2021-10-22  null 위  440 위  null 위
3   2021-10-23  null 위  410 위  null 위
4   2021-10-24  null 위  380 위  null 위
..         ...     ...    ...     ...
87  2022-01-15  null 위  411 위  null 위
88  2022-01-16  null 위  258 위  null 위
89  2022-01-17  null 위  282 위  null 위
90  2022-01-18  null 위  321 위  null 위
91  2022-01-19  null 위  286 위  null 위

[92 rows x 4 columns]

### 점유율 히스토리

#### 사용자 점유율

In [ ]:
#점유율 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[5]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 범위 생성 
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/슬립모니터_점유히스토리_사용자점유율.csv',index=True)

# df 확인 
df

<ipython-input-33-3be046f5e129>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[5]').click()
<ipython-input-33-3be046f5e129>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-33-3be046f5e129>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

          date And_IOS     And     IOS
0   2021-10-20  0.00 %  1.68 %  0.00 %
1   2021-10-21  0.00 %  1.67 %  0.00 %
2   2021-10-22  0.00 %  1.64 %  0.00 %
3   2021-10-23  0.00 %  1.60 %  0.00 %
4   2021-10-24  0.00 %  1.64 %  0.00 %
..         ...     ...     ...     ...
87  2022-01-15  0.00 %  1.57 %  0.00 %
88  2022-01-16  0.00 %  1.59 %  0.00 %
89  2022-01-17  0.00 %  1.60 %  0.00 %
90  2022-01-18  0.00 %  1.59 %  0.00 %
91  2022-01-19  0.00 %  1.59 %  0.00 %

[92 rows x 4 columns]

#### 사용시간 점유율

In [ ]:
# 사용시간 점유율 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 설정
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/슬립모니터_점유히스토리_사용시간점유율.csv',index=True)

# df 확인 
df

<ipython-input-35-23150533e9b7>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

          date And_IOS     And     IOS
0   2021-10-20  0.00 %  0.84 %  0.00 %
1   2021-10-21  0.00 %  0.79 %  0.00 %
2   2021-10-22  0.00 %  0.79 %  0.00 %
3   2021-10-23  0.00 %  0.76 %  0.00 %
4   2021-10-24  0.00 %  0.75 %  0.00 %
..         ...     ...     ...     ...
87  2022-01-15  0.00 %  0.73 %  0.00 %
88  2022-01-16  0.00 %  0.72 %  0.00 %
89  2022-01-17  0.00 %  0.78 %  0.00 %
90  2022-01-18  0.00 %  0.73 %  0.00 %
91  2022-01-19  0.00 %  0.70 %  0.00 %

[92 rows x 4 columns]

          date And_IOS     And     IOS
0   2021-10-20  0.00 %  0.84 %  0.00 %
1   2021-10-21  0.00 %  0.79 %  0.00 %
2   2021-10-22  0.00 %  0.79 %  0.00 %
3   2021-10-23  0.00 %  0.76 %  0.00 %
4   2021-10-24  0.00 %  0.75 %  0.00 %
..         ...     ...     ...     ...
87  2022-01-15  0.00 %  0.73 %  0.00 %
88  2022-01-16  0.00 %  0.72 %  0.00 %
89  2022-01-17  0.00 %  0.78 %  0.00 %
90  2022-01-18  0.00 %  0.73 %  0.00 %
91  2022-01-19  0.00 %  0.70 %  0.00 %

[92 rows x 4 columns]

from openpyxl import load_workbook, Workbook

wb = load_workbook('슬립모니터.xlsx')
ws = wb.active

wb.create_sheet('기본사용량_사용자수', 0)
wb.create_sheet('기본사용량_사용시간', 1)
wb.create_sheet('기본사용량_활성기기', 2)
wb.create_sheet('기본사용량_신규설치건수', 3)
wb.create_sheet('데모그래픽_사용자구성', 4)
wb.create_sheet('데모그래픽_연령별사용시간', 5)
wb.create_sheet('순위히스토리_사용자순위', 6)
wb.create_sheet('순위히스토리_사용시간순위', 7)
wb.create_sheet('점유율히스토리_사용자점유율', 8)
wb.create_sheet('점유율히스토리_사용시간점유율', 9)

for ws in wb.sheetnames:
    print(ws)

## 삼성 헬스 크롤링

### 기본 사용량

#### 사용자 수

In [ ]:
#모바일인덱스 슬립모니터 사이트 기본 사용량 분석으로 접속
browser.get('https://www.mobileindex.com/home?pkg=com.sleepmonitor.aio&route=app-detail%2Fapp-info%2Fsummary')
browser.implicitly_wait(time_to_wait=4)

In [ ]:
# https://www.mobileindex.com/home?pkg=com.sec.androi### 기본 사용량d.app.shealth&route=app-detail%2Fapp-info%2Fsummary

## Calm 크롤링

### 기본 사용량

#### 사용자 수

In [ ]:
# Calm분석으로 접속
browser.get('https://www.mobileindex.com/app/search?pkg=com.calm.android&route=app-detail%2Fapp-info%2Fsummary')
browser.implicitly_wait(time_to_wait=4)

In [ ]:
#기본 사용량 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[2]').click()
browser.implicitly_wait(time_to_wait=5)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

<ipython-input-15-d145b03918e0>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[2]').click()
<ipython-input-15-d145b03918e0>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-15-d145b03918e0>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

In [ ]:
# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

In [ ]:
# 범위 생성 
range = np.arange(184)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])


# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date','And'])

# df csv로 저장
df.to_csv('C:/R/Calm_기본사용량_사용자_수.csv',index=True)

# df 확인 
df

          date      And
0   2021-10-20  1,829 명
1   2021-10-21  1,763 명
2   2021-10-22  1,532 명
3   2021-10-23  1,320 명
4   2021-10-24  1,566 명
..         ...      ...
87  2022-01-15  1,748 명
88  2022-01-16  1,878 명
89  2022-01-17  1,998 명
90  2022-01-18  1,898 명
91  2022-01-19  1,951 명

[92 rows x 2 columns]

#### 사용 시간

In [ ]:
#사용 시간 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

#대기
browser.implicitly_wait(time_to_wait=3)    

# 범위 생성 
range = np.arange(274)

# 공란 리스트 생성 
date = []
Total_time = []
Personal_average_time = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 3 == 0:
        date.append(notice_list[i])
    elif i % 3 == 1: 
        Total_time.append(notice_list[i])
    elif i % 3 == 2: 
        Personal_average_time.append(notice_list[i])

        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, Total_time, Personal_average_time]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'Total_time', 'Personal_average_time'])

# df csv로 저장
df.to_csv('C:/R/Calm_기본사용량_사용_시간.csv',index=True)


# df 확인 
df

<ipython-input-19-700091c6823c>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

          date Total_time Personal_average_time
0   2021-10-20     494 시간               16.20 분
1   2021-10-21     361 시간               12.28 분
2   2021-10-22     380 시간               14.88 분
3   2021-10-23     315 시간               14.30 분
4   2021-10-24     365 시간               14.00 분
..         ...        ...                   ...
87  2022-01-15     510 시간               17.52 분
88  2022-01-16     574 시간               18.35 분
89  2022-01-17     549 시간               16.48 분
90  2022-01-18     484 시간               15.28 분
91  2022-01-19       None                  None

[92 rows x 3 columns]

#### 활성 기기

In [ ]:
# 활성 기기 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[3]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

#대기
browser.implicitly_wait(time_to_wait=3)    

# 범위 생성 
range = np.arange(12)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date','And'])

# df csv로 저장
df.to_csv('C:/R/Calm_기본사용량_활성기기.csv',index=True)

# df 확인 
df

<ipython-input-21-7b5f125798cc>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[3]').click()

      date        And
0  2021-07  102,028 대
1  2021-08  110,306 대
2  2021-09  111,649 대
3  2021-10  110,446 대
4  2021-11  106,988 대
5  2021-12  106,777 대

#### 신규 설치 건 수

In [ ]:
# 신규 설치 건 수 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[4]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

#대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(184)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])

        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And'])

# df csv로 저장
df.to_csv('C:/R/Calm_기본사용량_신규_설치건수.csv',index=True)

# df 확인 
df

<ipython-input-23-26dc59829a72>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[4]').click()

          date    And
0   2021-10-20  204 건
1   2021-10-21  151 건
2   2021-10-22  122 건
3   2021-10-23  147 건
4   2021-10-24  199 건
..         ...    ...
87  2022-01-15  561 건
88  2022-01-16  513 건
89  2022-01-17  374 건
90  2022-01-18  431 건
91  2022-01-19  502 건

[92 rows x 2 columns]

### 데모그래픽

#### 사용자 구성

In [ ]:
#데모그래픽 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[3]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(35)

# 공란 리스트 생성 
Start = []
End = []
Age = []
Male = []
Female = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 5 == 0:
        Start.append(notice_list[i])    
    elif i % 5 == 1: 
        End.append(notice_list[i])
    elif i % 5 == 2: 
        Age.append(notice_list[i])
    elif i % 5 == 3: 
        Male.append(notice_list[i])    
    elif i % 5 == 4: 
        Female.append(notice_list[i])    
        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([Start, End, Age, Male, Female]).transpose()

# 칼럼명 변경 
df.columns = (['Start', 'End', 'Age', 'Male', 'Female'])

# df csv로 저장
df.to_csv('C:/R/Calm_데모그래픽_사용자구성.csv',index=True)

# df 확인 
df

<ipython-input-24-af2313461f85>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[3]').click()
<ipython-input-24-af2313461f85>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-24-af2313461f85>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

        Start         End     Age     Male   Female
0  2021-10-20  2022-01-19      전체  34.18 %  65.82 %
1  2021-10-20  2022-01-19  10대 이하   1.33 %   1.72 %
2  2021-10-20  2022-01-19     20대   8.84 %  19.13 %
3  2021-10-20  2022-01-19     30대  10.33 %  18.01 %
4  2021-10-20  2022-01-19     40대   8.70 %  19.36 %
5  2021-10-20  2022-01-19     50대   4.11 %   6.24 %
6  2021-10-20  2022-01-19  60대 이상   0.87 %   1.35 %

#### 연령별 사용시간 구성

In [ ]:
# 활성 기기 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)
    
# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(35)

# 공란 리스트 생성 
Start = []
End = []
Age = []
Male = []
Female = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 5 == 0:
        Start.append(notice_list[i])    
    elif i % 5 == 1: 
        End.append(notice_list[i])
    elif i % 5 == 2: 
        Age.append(notice_list[i])
    elif i % 5 == 3: 
        Male.append(notice_list[i])    
    elif i % 5 == 4: 
        Female.append(notice_list[i])    
        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([Start, End, Age, Male, Female]).transpose()

# 칼럼명 변경 
df.columns = (['Start', 'End', 'Age', 'Male', 'Female'])

# df csv로 저장
df.to_csv('C:/R/Calm_데모그래픽_사용자구성.csv',index=True)

# df 확인 
df

<ipython-input-26-3c99d3a223a8>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

        Start         End     Age     Male   Female
0  2021-10-20  2022-01-19      전체  29.83 %  69.90 %
1  2021-10-20  2022-01-19  10대 이하   0.27 %   0.74 %
2  2021-10-20  2022-01-19     20대   5.22 %  12.78 %
3  2021-10-20  2022-01-19     30대   7.73 %  21.25 %
4  2021-10-20  2022-01-19     40대   9.81 %  26.70 %
5  2021-10-20  2022-01-19     50대   6.35 %   6.34 %
6  2021-10-20  2022-01-19  60대 이상   0.71 %   2.09 %

### 순위 히스토리

#### 사용자 순위

In [ ]:
#순위 히스토리 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[4]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span').click()
browser.implicitly_wait(time_to_wait=4)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)
    
# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(368)

# 공란 리스트 생성 
date = []
Total = []
And = []
IOS = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        Total.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, Total, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'Total', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/Calm_순위히스토리_사용자 순위.csv',index=True)

# df 확인 
df

<ipython-input-27-dc28ba05465c>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[4]').click()
<ipython-input-27-dc28ba05465c>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span').click()
<ipython-input-27-dc28ba05465c>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span/span/span[2]').click()

          date   Total    And     IOS
0   2021-10-20  null 위  147 위  null 위
1   2021-10-21  null 위  149 위  null 위
2   2021-10-22  null 위  220 위  null 위
3   2021-10-23  null 위  202 위  null 위
4   2021-10-24  null 위  199 위  null 위
..         ...     ...    ...     ...
87  2022-01-15  null 위  267 위  null 위
88  2022-01-16  null 위  110 위  null 위
89  2022-01-17  null 위  139 위  null 위
90  2022-01-18  null 위  182 위  null 위
91  2022-01-19  null 위  138 위  null 위

[92 rows x 4 columns]

#### 사용시간 순위

In [ ]:
# 사용시간 순위 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 범위 생성 
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/Calm_순위히스토리_사용시간순위.csv',index=True)

# df 확인 
df

<ipython-input-29-2acff28a8f2b>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

          date And_IOS    And     IOS
0   2021-10-20  null 위  322 위  null 위
1   2021-10-21  null 위  318 위  null 위
2   2021-10-22  null 위  440 위  null 위
3   2021-10-23  null 위  410 위  null 위
4   2021-10-24  null 위  380 위  null 위
..         ...     ...    ...     ...
87  2022-01-15  null 위  411 위  null 위
88  2022-01-16  null 위  258 위  null 위
89  2022-01-17  null 위  282 위  null 위
90  2022-01-18  null 위  321 위  null 위
91  2022-01-19  null 위  286 위  null 위

[92 rows x 4 columns]

### 점유율 히스토리

#### 사용자 점유율

In [ ]:
#점유율 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[5]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)
    
# 대기 
browser.implicitly_wait(time_to_wait=3)

# range 생성
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/Calm_점유히스토리_사용자점유율.csv',index=True)

# df 확인 
df

<ipython-input-30-658c76b87681>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[5]').click()
<ipython-input-30-658c76b87681>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-30-658c76b87681>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

          date And_IOS     And     IOS
0   2021-10-20  0.00 %  1.68 %  0.00 %
1   2021-10-21  0.00 %  1.67 %  0.00 %
2   2021-10-22  0.00 %  1.64 %  0.00 %
3   2021-10-23  0.00 %  1.60 %  0.00 %
4   2021-10-24  0.00 %  1.64 %  0.00 %
..         ...     ...     ...     ...
87  2022-01-15  0.00 %  1.57 %  0.00 %
88  2022-01-16  0.00 %  1.59 %  0.00 %
89  2022-01-17  0.00 %  1.60 %  0.00 %
90  2022-01-18  0.00 %  1.59 %  0.00 %
91  2022-01-19  0.00 %  1.59 %  0.00 %

[92 rows x 4 columns]

#### 사용시간 점유율

In [ ]:
# 사용시간 점유율 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 설정
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/Calm_점유히스토리_사용시간점유율.csv',index=True)

# df 확인 
df\\ㄱ\\\\\

<ipython-input-32-16e98224ec0f>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

          date And_IOS     And     IOS
0   2021-10-20  0.00 %  0.84 %  0.00 %
1   2021-10-21  0.00 %  0.79 %  0.00 %
2   2021-10-22  0.00 %  0.79 %  0.00 %
3   2021-10-23  0.00 %  0.76 %  0.00 %
4   2021-10-24  0.00 %  0.75 %  0.00 %
..         ...     ...     ...     ...
87  2022-01-15  0.00 %  0.73 %  0.00 %
88  2022-01-16  0.00 %  0.72 %  0.00 %
89  2022-01-17  0.00 %  0.78 %  0.00 %
90  2022-01-18  0.00 %  0.73 %  0.00 %
91  2022-01-19  0.00 %  0.70 %  0.00 %

[92 rows x 4 columns]

## sleep as android  크롤링

### 기본 사용량

#### 사용자 수

In [ ]:
# sleep as android로 접속 
browser.get('https://www.mobileindex.com/app/search?pkg=com.urbandroid.sleep&route=app-detail%2Fusage-info%2Fdemographic-analysis')
browser.implicitly_wait(time_to_wait=4)

In [ ]:
#기본 사용량 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[2]').click()
browser.implicitly_wait(time_to_wait=5)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 범위 생성 
range = np.arange(184)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])


# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date','And'])

# df csv로 저장
df.to_csv('C:/R/SleepAsAndroid_기본사용량_사용자_수.csv',index=True)

# df 확인 
df

<ipython-input-15-fbcc03e781e7>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[2]').click()
<ipython-input-15-fbcc03e781e7>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-15-fbcc03e781e7>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

          date      And
0   2021-10-20  5,212 명
1   2021-10-21  5,107 명
2   2021-10-22  5,104 명
3   2021-10-23  3,967 명
4   2021-10-24  4,146 명
..         ...      ...
87  2022-01-15  3,783 명
88  2022-01-16  3,840 명
89  2022-01-17  4,935 명
90  2022-01-18  4,949 명
91  2022-01-19  4,820 명

[92 rows x 2 columns]

#### 사용 시간

In [ ]:
#사용 시간 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

#대기
browser.implicitly_wait(time_to_wait=3)    

# 범위 생성 
range = np.arange(274)

# 공란 리스트 생성 
date = []
Total_time = []
Personal_average_time = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 3 == 0:
        date.append(notice_list[i])
    elif i % 3 == 1: 
        Total_time.append(notice_list[i])
    elif i % 3 == 2: 
        Personal_average_time.append(notice_list[i])

        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, Total_time, Personal_average_time]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'Total_time', 'Personal_average_time'])

# df csv로 저장
df.to_csv('C:/R/SleepAsAndroid_기본사용량_사용_시간.csv',index=True)


# df 확인 
df

<ipython-input-17-a0a685ae7c9c>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

          date Total_time Personal_average_time
0   2021-10-20     699 시간                8.05 분
1   2021-10-21     729 시간                8.57 분
2   2021-10-22     802 시간                9.43 분
3   2021-10-23     569 시간                8.60 분
4   2021-10-24     537 시간                7.78 분
..         ...        ...                   ...
87  2022-01-15     620 시간                9.83 분
88  2022-01-16     595 시간                9.28 분
89  2022-01-17     648 시간                7.87 분
90  2022-01-18     748 시간                9.07 분
91  2022-01-19       None                  None

[92 rows x 3 columns]

#### 활성 기기

In [ ]:
# 활성 기기 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[3]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

#대기
browser.implicitly_wait(time_to_wait=3)    

# 범위 생성 
range = np.arange(12)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date','And'])

# df csv로 저장
df.to_csv('C:/R/SleepAsAndroid_기본사용량_활성기기.csv',index=True)

# df 확인 
df

<ipython-input-19-5d5096eaec82>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[3]').click()

      date       And
0  2021-07  27,007 대
1  2021-08  26,415 대
2  2021-09  25,831 대
3  2021-10  25,652 대
4  2021-11  25,493 대
5  2021-12  24,920 대

#### 신규 설치 건 수

In [ ]:
# 신규 설치 건 수 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[4]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

#대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(184)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])

        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And'])

# df csv로 저장
df.to_csv('C:/R/SleepAsAndroid_기본사용량_신규_설치건수.csv',index=True)

# df 확인 
df

<ipython-input-21-d20f4194f27f>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[4]').click()

          date   And
0   2021-10-20  16 건
1   2021-10-21  17 건
2   2021-10-22  33 건
3   2021-10-23   4 건
4   2021-10-24     -
..         ...   ...
87  2022-01-15   9 건
88  2022-01-16  13 건
89  2022-01-17  19 건
90  2022-01-18   4 건
91  2022-01-19  15 건

[92 rows x 2 columns]

### 데모그래픽

#### 사용자 구성

In [ ]:
#데모그래픽 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[3]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(35)

# 공란 리스트 생성 
Start = []
End = []
Age = []
Male = []
Female = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 5 == 0:
        Start.append(notice_list[i])    
    elif i % 5 == 1: 
        End.append(notice_list[i])
    elif i % 5 == 2: 
        Age.append(notice_list[i])
    elif i % 5 == 3: 
        Male.append(notice_list[i])    
    elif i % 5 == 4: 
        Female.append(notice_list[i])    
        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([Start, End, Age, Male, Female]).transpose()

# 칼럼명 변경 
df.columns = (['Start', 'End', 'Age', 'Male', 'Female'])

# df csv로 저장
df.to_csv('C:/R/SleepAsAndroid_데모그래픽_사용자구성.csv',index=True)

# df 확인 
df

<ipython-input-22-db7bfc4cddd8>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[3]').click()
<ipython-input-22-db7bfc4cddd8>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-22-db7bfc4cddd8>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

        Start         End     Age     Male   Female
0  2021-10-20  2022-01-19      전체  48.75 %  51.25 %
1  2021-10-20  2022-01-19  10대 이하   1.63 %   3.23 %
2  2021-10-20  2022-01-19     20대  19.12 %  25.84 %
3  2021-10-20  2022-01-19     30대  16.36 %  13.49 %
4  2021-10-20  2022-01-19     40대   8.43 %   4.36 %
5  2021-10-20  2022-01-19     50대   2.71 %   3.11 %
6  2021-10-20  2022-01-19  60대 이상   0.50 %   1.23 %

#### 연령별 사용시간 구성

In [ ]:
# 활성 기기 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)
    
# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(35)

# 공란 리스트 생성 
Start = []
End = []
Age = []
Male = []
Female = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 5 == 0:
        Start.append(notice_list[i])    
    elif i % 5 == 1: 
        End.append(notice_list[i])
    elif i % 5 == 2: 
        Age.append(notice_list[i])
    elif i % 5 == 3: 
        Male.append(notice_list[i])    
    elif i % 5 == 4: 
        Female.append(notice_list[i])    
        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([Start, End, Age, Male, Female]).transpose()

# 칼럼명 변경 
df.columns = (['Start', 'End', 'Age', 'Male', 'Female'])

# df csv로 저장
df.to_csv('C:/R/SleepAsAndroid_데모그래픽_사용자구성.csv',index=True)

# df 확인 
df

<ipython-input-24-6310d04d7764>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

        Start         End     Age     Male   Female
0  2021-10-20  2022-01-19      전체  52.84 %  45.23 %
1  2021-10-20  2022-01-19  10대 이하   1.93 %   1.67 %
2  2021-10-20  2022-01-19     20대  21.72 %  29.09 %
3  2021-10-20  2022-01-19     30대  19.02 %   9.15 %
4  2021-10-20  2022-01-19     40대   9.62 %   3.09 %
5  2021-10-20  2022-01-19     50대   1.80 %   1.34 %
6  2021-10-20  2022-01-19  60대 이상   0.67 %   0.90 %

### 순위 히스토리

#### 사용자 순위

In [ ]:
#순위 히스토리 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[4]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span').click()
browser.implicitly_wait(time_to_wait=4)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)
    
# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(368)

# 공란 리스트 생성 
date = []
Total = []
And = []
IOS = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        Total.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, Total, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'Total', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/SleepAsAndroid_순위히스토리_사용자 순위.csv',index=True)

# df 확인 
df

<ipython-input-25-02c47940854c>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[4]').click()
<ipython-input-25-02c47940854c>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span').click()
<ipython-input-25-02c47940854c>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span/span/span[2]').click()

          date   Total    And     IOS
0   2021-10-20  null 위  147 위  null 위
1   2021-10-21  null 위  149 위  null 위
2   2021-10-22  null 위  220 위  null 위
3   2021-10-23  null 위  202 위  null 위
4   2021-10-24  null 위  199 위  null 위
..         ...     ...    ...     ...
87  2022-01-15  null 위  267 위  null 위
88  2022-01-16  null 위  110 위  null 위
89  2022-01-17  null 위  139 위  null 위
90  2022-01-18  null 위  182 위  null 위
91  2022-01-19  null 위  138 위  null 위

[92 rows x 4 columns]

#### 사용시간 순위

In [ ]:
# 사용시간 순위 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 범위 생성 
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/SleepAsAndroid_순위히스토리_사용시간순위.csv',index=True)

# df 확인 
df

<ipython-input-27-a352a02d1c5c>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

          date And_IOS    And     IOS
0   2021-10-20  null 위  322 위  null 위
1   2021-10-21  null 위  318 위  null 위
2   2021-10-22  null 위  440 위  null 위
3   2021-10-23  null 위  410 위  null 위
4   2021-10-24  null 위  380 위  null 위
..         ...     ...    ...     ...
87  2022-01-15  null 위  411 위  null 위
88  2022-01-16  null 위  258 위  null 위
89  2022-01-17  null 위  282 위  null 위
90  2022-01-18  null 위  321 위  null 위
91  2022-01-19  null 위  286 위  null 위

[92 rows x 4 columns]

### 점유율 히스토리

#### 사용자 점유율

In [ ]:
#점유율 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[5]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)
    
# 대기 
browser.implicitly_wait(time_to_wait=3)

# range 생성
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/SleepAsAndroid_점유히스토리_사용자점유율.csv',index=True)

# df 확인 
df

<ipython-input-28-58469b3e6e65>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[5]').click()
<ipython-input-28-58469b3e6e65>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-28-58469b3e6e65>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

          date And_IOS     And     IOS
0   2021-10-20  0.00 %  1.68 %  0.00 %
1   2021-10-21  0.00 %  1.67 %  0.00 %
2   2021-10-22  0.00 %  1.64 %  0.00 %
3   2021-10-23  0.00 %  1.60 %  0.00 %
4   2021-10-24  0.00 %  1.64 %  0.00 %
..         ...     ...     ...     ...
87  2022-01-15  0.00 %  1.57 %  0.00 %
88  2022-01-16  0.00 %  1.59 %  0.00 %
89  2022-01-17  0.00 %  1.60 %  0.00 %
90  2022-01-18  0.00 %  1.59 %  0.00 %
91  2022-01-19  0.00 %  1.59 %  0.00 %

[92 rows x 4 columns]

#### 사용시간 점유율

In [ ]:
# 사용시간 점유율 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 설정
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/SleepAsAndroid_점유히스토리_사용시간점유율.csv',index=True)

# df 확인 
df

<ipython-input-30-ff42c3a11c45>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

          date And_IOS     And     IOS
0   2021-10-20  0.00 %  0.84 %  0.00 %
1   2021-10-21  0.00 %  0.79 %  0.00 %
2   2021-10-22  0.00 %  0.79 %  0.00 %
3   2021-10-23  0.00 %  0.76 %  0.00 %
4   2021-10-24  0.00 %  0.75 %  0.00 %
..         ...     ...     ...     ...
87  2022-01-15  0.00 %  0.73 %  0.00 %
88  2022-01-16  0.00 %  0.72 %  0.00 %
89  2022-01-17  0.00 %  0.78 %  0.00 %
90  2022-01-18  0.00 %  0.73 %  0.00 %
91  2022-01-19  0.00 %  0.70 %  0.00 %

[92 rows x 4 columns]

## 스노어랩  크롤링

### 기본 사용량

#### 사용자 수

In [ ]:
# 스노어랩으로 접속 
browser.get('https://www.mobileindex.com/app/search?pkg=com.snorelab.app&route=app-detail%2Fusage-info%2Fdemographic-analysis')
browser.implicitly_wait(time_to_wait=4)

In [ ]:
#기본 사용량 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[2]').click()
browser.implicitly_wait(time_to_wait=5)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 범위 생성 
range = np.arange(184)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])


# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date','And'])

# df csv로 저장
df.to_csv('C:/R/스노어랩_기본사용량_사용자_수.csv',index=True)

# df 확인 
df

<ipython-input-15-aa6b219a208a>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[2]').click()
<ipython-input-15-aa6b219a208a>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-15-aa6b219a208a>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

          date      And
0   2021-10-20  2,357 명
1   2021-10-21  2,337 명
2   2021-10-22  2,222 명
3   2021-10-23  2,035 명
4   2021-10-24  2,243 명
..         ...      ...
87  2022-01-15  2,022 명
88  2022-01-16  2,258 명
89  2022-01-17  2,580 명
90  2022-01-18  2,510 명
91  2022-01-19  2,434 명

[92 rows x 2 columns]

#### 사용 시간

In [ ]:
#사용 시간 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

#대기
browser.implicitly_wait(time_to_wait=3)    

# 범위 생성 
range = np.arange(274)

# 공란 리스트 생성 
date = []
Total_time = []
Personal_average_time = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 3 == 0:
        date.append(notice_list[i])
    elif i % 3 == 1: 
        Total_time.append(notice_list[i])
    elif i % 3 == 2: 
        Personal_average_time.append(notice_list[i])

        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, Total_time, Personal_average_time]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'Total_time', 'Personal_average_time'])

# df csv로 저장
df.to_csv('C:/R/스노어랩_기본사용량_사용_시간.csv',index=True)


# df 확인 
df

<ipython-input-18-f6cdf6546b6e>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

          date Total_time Personal_average_time
0   2021-10-20   4,897 시간              124.67 분
1   2021-10-21   5,028 시간              129.10 분
2   2021-10-22   4,365 시간              117.87 분
3   2021-10-23   3,924 시간              115.68 분
4   2021-10-24   4,469 시간              119.53 분
..         ...        ...                   ...
87  2022-01-15   4,195 시간              124.48 분
88  2022-01-16   4,620 시간              122.75 분
89  2022-01-17   5,016 시간              116.65 분
90  2022-01-18   5,134 시간              122.73 분
91  2022-01-19       None                  None

[92 rows x 3 columns]

#### 활성 기기

In [ ]:
# 활성 기기 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[3]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

#대기
browser.implicitly_wait(time_to_wait=3)    

# 범위 생성 
range = np.arange(12)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date','And'])

# df csv로 저장
df.to_csv('C:/R/스노어랩_기본사용량_활성기기.csv',index=True)

# df 확인 
df

<ipython-input-20-bd11837703bb>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[3]').click()

      date       And
0  2021-07  58,082 대
1  2021-08  57,712 대
2  2021-09  56,850 대
3  2021-10  55,825 대
4  2021-11  54,836 대
5  2021-12  54,015 대

#### 신규 설치 건 수

In [ ]:
# 신규 설치 건 수 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[4]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

#대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(184)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])

        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And'])

# df csv로 저장
df.to_csv('C:/R/스노어랩_기본사용량_신규_설치건수.csv',index=True)

# df 확인 
df

<ipython-input-22-1ef7190627fd>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[4]').click()

          date    And
0   2021-10-20   84 건
1   2021-10-21   52 건
2   2021-10-22   56 건
3   2021-10-23  105 건
4   2021-10-24   91 건
..         ...    ...
87  2022-01-15   49 건
88  2022-01-16   52 건
89  2022-01-17   65 건
90  2022-01-18   47 건
91  2022-01-19   55 건

[92 rows x 2 columns]

### 데모그래픽

#### 사용자 구성

In [ ]:
#데모그래픽 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[3]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(35)

# 공란 리스트 생성 
Start = []
End = []
Age = []
Male = []
Female = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 5 == 0:
        Start.append(notice_list[i])    
    elif i % 5 == 1: 
        End.append(notice_list[i])
    elif i % 5 == 2: 
        Age.append(notice_list[i])
    elif i % 5 == 3: 
        Male.append(notice_list[i])    
    elif i % 5 == 4: 
        Female.append(notice_list[i])    
        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([Start, End, Age, Male, Female]).transpose()

# 칼럼명 변경 
df.columns = (['Start', 'End', 'Age', 'Male', 'Female'])

# df csv로 저장
df.to_csv('C:/R/스노어랩_데모그래픽_사용자구성.csv',index=True)

# df 확인 
df

<ipython-input-23-49b8760345e9>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[3]').click()
<ipython-input-23-49b8760345e9>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-23-49b8760345e9>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

        Start         End     Age     Male   Female
0  2021-10-20  2022-01-19      전체  50.64 %  49.36 %
1  2021-10-20  2022-01-19  10대 이하   0.72 %   1.39 %
2  2021-10-20  2022-01-19     20대   8.75 %  11.14 %
3  2021-10-20  2022-01-19     30대  14.64 %  13.22 %
4  2021-10-20  2022-01-19     40대  15.70 %  12.03 %
5  2021-10-20  2022-01-19     50대   9.26 %   9.94 %
6  2021-10-20  2022-01-19  60대 이상   1.56 %   1.65 %

#### 연령별 사용시간 구성

In [ ]:
# 활성 기기 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)
    
# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(35)

# 공란 리스트 생성 
Start = []
End = []
Age = []
Male = []
Female = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 5 == 0:
        Start.append(notice_list[i])    
    elif i % 5 == 1: 
        End.append(notice_list[i])
    elif i % 5 == 2: 
        Age.append(notice_list[i])
    elif i % 5 == 3: 
        Male.append(notice_list[i])    
    elif i % 5 == 4: 
        Female.append(notice_list[i])    
        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([Start, End, Age, Male, Female]).transpose()

# 칼럼명 변경 
df.columns = (['Start', 'End', 'Age', 'Male', 'Female'])

# df csv로 저장
df.to_csv('C:/R/스노어랩_데모그래픽_사용자구성.csv',index=True)

# df 확인 
df

<ipython-input-25-656035621ba0>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

        Start         End     Age     Male   Female
0  2021-10-20  2022-01-19      전체  51.30 %  47.77 %
1  2021-10-20  2022-01-19  10대 이하   0.93 %   0.33 %
2  2021-10-20  2022-01-19     20대   5.92 %   8.22 %
3  2021-10-20  2022-01-19     30대  12.97 %  13.78 %
4  2021-10-20  2022-01-19     40대  17.31 %  13.08 %
5  2021-10-20  2022-01-19     50대  12.70 %  10.75 %
6  2021-10-20  2022-01-19  60대 이상   2.40 %   1.61 %

### 순위 히스토리

#### 사용자 순위

In [ ]:
#순위 히스토리 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[4]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span').click()
browser.implicitly_wait(time_to_wait=4)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)
    
# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(368)

# 공란 리스트 생성 
date = []
Total = []
And = []
IOS = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        Total.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, Total, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'Total', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/스노어랩_순위히스토리_사용자 순위.csv',index=True)

# df 확인 
df

<ipython-input-26-a420a662b4a1>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[4]').click()
<ipython-input-26-a420a662b4a1>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span').click()
<ipython-input-26-a420a662b4a1>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span/span/span[2]').click()

          date   Total    And     IOS
0   2021-10-20  null 위  147 위  null 위
1   2021-10-21  null 위  149 위  null 위
2   2021-10-22  null 위  220 위  null 위
3   2021-10-23  null 위  202 위  null 위
4   2021-10-24  null 위  199 위  null 위
..         ...     ...    ...     ...
87  2022-01-15  null 위  267 위  null 위
88  2022-01-16  null 위  110 위  null 위
89  2022-01-17  null 위  139 위  null 위
90  2022-01-18  null 위  182 위  null 위
91  2022-01-19  null 위  138 위  null 위

[92 rows x 4 columns]

#### 사용시간 순위

In [ ]:
# 사용시간 순위 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 범위 생성 
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/스노어랩_순위히스토리_사용시간순위.csv',index=True)

# df 확인 
df

<ipython-input-28-a62dcf65a2a6>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

          date And_IOS    And     IOS
0   2021-10-20  null 위  322 위  null 위
1   2021-10-21  null 위  318 위  null 위
2   2021-10-22  null 위  440 위  null 위
3   2021-10-23  null 위  410 위  null 위
4   2021-10-24  null 위  380 위  null 위
..         ...     ...    ...     ...
87  2022-01-15  null 위  411 위  null 위
88  2022-01-16  null 위  258 위  null 위
89  2022-01-17  null 위  282 위  null 위
90  2022-01-18  null 위  321 위  null 위
91  2022-01-19  null 위  286 위  null 위

[92 rows x 4 columns]

### 점유율 히스토리

#### 사용자 점유율

In [ ]:
#점유율 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[5]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)
    
# 대기 
browser.implicitly_wait(time_to_wait=3)

# range 생성
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/스노어랩_점유히스토리_사용자점유율.csv',index=True)

# df 확인 
df

<ipython-input-29-69ad7f60e53a>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[5]').click()
<ipython-input-29-69ad7f60e53a>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-29-69ad7f60e53a>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

          date And_IOS     And     IOS
0   2021-10-20  0.00 %  1.68 %  0.00 %
1   2021-10-21  0.00 %  1.67 %  0.00 %
2   2021-10-22  0.00 %  1.64 %  0.00 %
3   2021-10-23  0.00 %  1.60 %  0.00 %
4   2021-10-24  0.00 %  1.64 %  0.00 %
..         ...     ...     ...     ...
87  2022-01-15  0.00 %  1.57 %  0.00 %
88  2022-01-16  0.00 %  1.59 %  0.00 %
89  2022-01-17  0.00 %  1.60 %  0.00 %
90  2022-01-18  0.00 %  1.59 %  0.00 %
91  2022-01-19  0.00 %  1.59 %  0.00 %

[92 rows x 4 columns]

#### 사용시간 점유율

In [ ]:
# 사용시간 점유율 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 설정
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/스노어랩_점유히스토리_사용시간점유율.csv',index=True)

# df 확인 
df

<ipython-input-31-7d479a32ee49>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

          date And_IOS     And     IOS
0   2021-10-20  0.00 %  0.84 %  0.00 %
1   2021-10-21  0.00 %  0.79 %  0.00 %
2   2021-10-22  0.00 %  0.79 %  0.00 %
3   2021-10-23  0.00 %  0.76 %  0.00 %
4   2021-10-24  0.00 %  0.75 %  0.00 %
..         ...     ...     ...     ...
87  2022-01-15  0.00 %  0.73 %  0.00 %
88  2022-01-16  0.00 %  0.72 %  0.00 %
89  2022-01-17  0.00 %  0.78 %  0.00 %
90  2022-01-18  0.00 %  0.73 %  0.00 %
91  2022-01-19  0.00 %  0.70 %  0.00 %

[92 rows x 4 columns]

## 수면소리  크롤링

### 기본 사용량

#### 사용자 수

In [ ]:
# 수면소리로 접속 
browser.get('https://www.mobileindex.com/app/search?pkg=net.metapps.sleepsounds&route=app-detail%2Fusage-info%2Fdemographic-analysis')
browser.implicitly_wait(time_to_wait=4)

In [ ]:
#기본 사용량 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[2]').click()
browser.implicitly_wait(time_to_wait=5)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 범위 생성 
range = np.arange(184)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])


# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date','And'])

# df csv로 저장
df.to_csv('C:/R/수면소리_기본사용량_사용자_수.csv',index=True)

# df 확인 
df

<ipython-input-15-bb37ea2cb012>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[2]').click()
<ipython-input-15-bb37ea2cb012>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-15-bb37ea2cb012>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

          date      And
0   2021-10-20  1,207 명
1   2021-10-21  1,148 명
2   2021-10-22  1,098 명
3   2021-10-23  1,001 명
4   2021-10-24  1,243 명
..         ...      ...
87  2022-01-15    902 명
88  2022-01-16  1,038 명
89  2022-01-17  1,055 명
90  2022-01-18  1,025 명
91  2022-01-19    974 명

[92 rows x 2 columns]

#### 사용 시간

In [ ]:
#사용 시간 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

#대기
browser.implicitly_wait(time_to_wait=3)    

# 범위 생성 
range = np.arange(274)

# 공란 리스트 생성 
date = []
Total_time = []
Personal_average_time = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 3 == 0:
        date.append(notice_list[i])
    elif i % 3 == 1: 
        Total_time.append(notice_list[i])
    elif i % 3 == 2: 
        Personal_average_time.append(notice_list[i])

        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, Total_time, Personal_average_time]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'Total_time', 'Personal_average_time'])

# df csv로 저장
df.to_csv('C:/R/수면소리_기본사용량_사용_시간.csv',index=True)


# df 확인 
df

<ipython-input-17-a2354c98ac78>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

          date Total_time Personal_average_time
0   2021-10-20      33 시간                1.63 분
1   2021-10-21      27 시간                1.40 분
2   2021-10-22      40 시간                2.18 분
3   2021-10-23      35 시간                2.08 분
4   2021-10-24      36 시간                1.77 분
..         ...        ...                   ...
87  2022-01-15      40 시간                2.63 분
88  2022-01-16      28 시간                1.62 분
89  2022-01-17      23 시간                1.28 분
90  2022-01-18      45 시간                2.63 분
91  2022-01-19       None                  None

[92 rows x 3 columns]

#### 활성 기기

In [ ]:
# 활성 기기 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[3]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

#대기
browser.implicitly_wait(time_to_wait=3)    

# 범위 생성 
range = np.arange(12)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date','And'])

# df csv로 저장
df.to_csv('C:/R/수면소리_기본사용량_활성기기.csv',index=True)

# df 확인 
df

<ipython-input-19-f2721dfefa50>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[3]').click()

      date       And
0  2021-07  25,826 대
1  2021-08  24,554 대
2  2021-09  24,274 대
3  2021-10  24,308 대
4  2021-11  23,658 대
5  2021-12  22,653 대

#### 신규 설치 건 수

In [ ]:
# 신규 설치 건 수 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[4]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

#대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(184)

# 공란 리스트 생성 
date = []
And = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 2 == 0:
        date.append(notice_list[i])
    elif i % 2 == 1: 
        And.append(notice_list[i])

        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And'])

# df csv로 저장
df.to_csv('C:/R/수면소리_기본사용량_신규_설치건수.csv',index=True)

# df 확인 
df

<ipython-input-21-7eb9239d2294>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[4]').click()

          date   And
0   2021-10-20  21 건
1   2021-10-21   4 건
2   2021-10-22  11 건
3   2021-10-23  23 건
4   2021-10-24  21 건
..         ...   ...
87  2022-01-15  29 건
88  2022-01-16  37 건
89  2022-01-17  21 건
90  2022-01-18  16 건
91  2022-01-19  22 건

[92 rows x 2 columns]

### 데모그래픽

#### 사용자 구성

In [ ]:
#데모그래픽 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[3]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(35)

# 공란 리스트 생성 
Start = []
End = []
Age = []
Male = []
Female = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 5 == 0:
        Start.append(notice_list[i])    
    elif i % 5 == 1: 
        End.append(notice_list[i])
    elif i % 5 == 2: 
        Age.append(notice_list[i])
    elif i % 5 == 3: 
        Male.append(notice_list[i])    
    elif i % 5 == 4: 
        Female.append(notice_list[i])    
        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([Start, End, Age, Male, Female]).transpose()

# 칼럼명 변경 
df.columns = (['Start', 'End', 'Age', 'Male', 'Female'])

# df csv로 저장
df.to_csv('C:/R/수면소리_데모그래픽_사용자구성.csv',index=True)

# df 확인 
df

<ipython-input-22-6d97f0ea3cb5>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[3]').click()
<ipython-input-22-6d97f0ea3cb5>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-22-6d97f0ea3cb5>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

        Start         End     Age     Male   Female
0  2021-10-20  2022-01-19      전체  44.43 %  55.57 %
1  2021-10-20  2022-01-19  10대 이하   0.83 %   1.94 %
2  2021-10-20  2022-01-19     20대   5.99 %   8.56 %
3  2021-10-20  2022-01-19     30대  14.96 %  18.85 %
4  2021-10-20  2022-01-19     40대  13.64 %  16.00 %
5  2021-10-20  2022-01-19     50대   7.47 %   7.97 %
6  2021-10-20  2022-01-19  60대 이상   1.55 %   2.25 %

#### 연령별 사용시간 구성

In [ ]:
# 활성 기기 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)
    
# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(35)

# 공란 리스트 생성 
Start = []
End = []
Age = []
Male = []
Female = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 5 == 0:
        Start.append(notice_list[i])    
    elif i % 5 == 1: 
        End.append(notice_list[i])
    elif i % 5 == 2: 
        Age.append(notice_list[i])
    elif i % 5 == 3: 
        Male.append(notice_list[i])    
    elif i % 5 == 4: 
        Female.append(notice_list[i])    
        
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([Start, End, Age, Male, Female]).transpose()

# 칼럼명 변경 
df.columns = (['Start', 'End', 'Age', 'Male', 'Female'])

# df csv로 저장
df.to_csv('C:/R/수면소리_데모그래픽_사용자구성.csv',index=True)

# df 확인 
df

<ipython-input-24-7fdaecf1dc3c>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

        Start         End     Age     Male   Female
0  2021-10-20  2022-01-19      전체  55.62 %  43.85 %
1  2021-10-20  2022-01-19  10대 이하   0.54 %   1.62 %
2  2021-10-20  2022-01-19     20대  10.17 %   3.86 %
3  2021-10-20  2022-01-19     30대   9.92 %  11.77 %
4  2021-10-20  2022-01-19     40대  26.04 %  15.00 %
5  2021-10-20  2022-01-19     50대   8.14 %   9.34 %
6  2021-10-20  2022-01-19  60대 이상   1.34 %   2.25 %

### 순위 히스토리

#### 사용자 순위

In [ ]:
#순위 히스토리 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[4]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span').click()
browser.implicitly_wait(time_to_wait=4)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)
    
# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 생성 
range = np.arange(368)

# 공란 리스트 생성 
date = []
Total = []
And = []
IOS = []

# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        Total.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, Total, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'Total', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/수면소리_순위히스토리_사용자 순위.csv',index=True)

# df 확인 
df

<ipython-input-25-9207bf795756>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[4]').click()
<ipython-input-25-9207bf795756>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span').click()
<ipython-input-25-9207bf795756>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div/div[2]/span/span/span[2]').click()

          date   Total    And     IOS
0   2021-10-20  null 위  147 위  null 위
1   2021-10-21  null 위  149 위  null 위
2   2021-10-22  null 위  220 위  null 위
3   2021-10-23  null 위  202 위  null 위
4   2021-10-24  null 위  199 위  null 위
..         ...     ...    ...     ...
87  2022-01-15  null 위  267 위  null 위
88  2022-01-16  null 위  110 위  null 위
89  2022-01-17  null 위  139 위  null 위
90  2022-01-18  null 위  182 위  null 위
91  2022-01-19  null 위  138 위  null 위

[92 rows x 4 columns]

#### 사용시간 순위

In [ ]:
# 사용시간 순위 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 범위 생성 
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/수면소리_순위히스토리_사용시간순위.csv',index=True)

# df 확인 
df

<ipython-input-27-3db6e635063d>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

          date And_IOS    And     IOS
0   2021-10-20  null 위  322 위  null 위
1   2021-10-21  null 위  318 위  null 위
2   2021-10-22  null 위  440 위  null 위
3   2021-10-23  null 위  410 위  null 위
4   2021-10-24  null 위  380 위  null 위
..         ...     ...    ...     ...
87  2022-01-15  null 위  411 위  null 위
88  2022-01-16  null 위  258 위  null 위
89  2022-01-17  null 위  282 위  null 위
90  2022-01-18  null 위  321 위  null 위
91  2022-01-19  null 위  286 위  null 위

[92 rows x 4 columns]

### 점유율 히스토리

#### 사용자 점유율

In [ ]:
#점유율 분석 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[5]').click()
browser.implicitly_wait(time_to_wait=3)

#차트 더보기 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

#테이블 클릭
browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)
    
# 대기 
browser.implicitly_wait(time_to_wait=3)

# range 생성
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/수면소리_점유히스토리_사용자점유율.csv',index=True)

# df 확인 
df

<ipython-input-28-c232e491ac0c>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/nav/div/div[2]/button[5]').click()
<ipython-input-28-c232e491ac0c>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]').click()
<ipython-input-28-c232e491ac0c>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="page-floating-scroll-page"]/section/div[4]/div[1]/div[2]/span[2]/span/span[2]').click()

          date And_IOS     And     IOS
0   2021-10-20  0.00 %  1.68 %  0.00 %
1   2021-10-21  0.00 %  1.67 %  0.00 %
2   2021-10-22  0.00 %  1.64 %  0.00 %
3   2021-10-23  0.00 %  1.60 %  0.00 %
4   2021-10-24  0.00 %  1.64 %  0.00 %
..         ...     ...     ...     ...
87  2022-01-15  0.00 %  1.57 %  0.00 %
88  2022-01-16  0.00 %  1.59 %  0.00 %
89  2022-01-17  0.00 %  1.60 %  0.00 %
90  2022-01-18  0.00 %  1.59 %  0.00 %
91  2022-01-19  0.00 %  1.59 %  0.00 %

[92 rows x 4 columns]

#### 사용시간 점유율

In [ ]:
# 사용시간 점유율 클릭 
browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()
browser.implicitly_wait(time_to_wait=3)

# 해당 페이지 소스 전부 가져오기
html = browser.page_source

# html parser..? 다 가져오기 
soup = BeautifulSoup(html, 'html.parser')

# 아래의 정보를 다 가져오기 
notices = soup.select('div.data > table > tbody > tr > td')

# 공란 리스트 생성 
notice_list = []

# 리스트에 해당 내용을 가져오는 반복문 생성 
for n in notices:
    notice_text = n.text.strip()
    notice_list.append(notice_text)

# 대기
browser.implicitly_wait(time_to_wait=3)

# 범위 설정
range = np.arange(368)

# 공란 리스트 생성 
date = []
And_IOS = []
And = []
IOS = []



# 각 리스트에 데이터 할당하는 반복문 생성 
for i in range:
    if i % 4 == 0:
        date.append(notice_list[i])
    elif i % 4 == 1: 
        And_IOS.append(notice_list[i])
    elif i % 4 == 2: 
        And.append(notice_list[i])
    elif i % 4 == 3: 
        IOS.append(notice_list[i])

        
                
# 데이터가 채워진 리스트를 df 데이터 프레임에 할당한 후 Transpose 
df = pd.DataFrame([date, And_IOS, And, IOS]).transpose()

# 칼럼명 변경 
df.columns = (['date', 'And_IOS', 'And', 'IOS'])

# df csv로 저장
df.to_csv('C:/R/수면소리_점유히스토리_사용시간점유율.csv',index=True)

# df 확인 
df

<ipython-input-30-52cb02bf2545>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath('//*[@id="floating-page-id"]/div/div/div[2]/div/button[2]').click()

          date And_IOS     And     IOS
0   2021-10-20  0.00 %  0.84 %  0.00 %
1   2021-10-21  0.00 %  0.79 %  0.00 %
2   2021-10-22  0.00 %  0.79 %  0.00 %
3   2021-10-23  0.00 %  0.76 %  0.00 %
4   2021-10-24  0.00 %  0.75 %  0.00 %
..         ...     ...     ...     ...
87  2022-01-15  0.00 %  0.73 %  0.00 %
88  2022-01-16  0.00 %  0.72 %  0.00 %
89  2022-01-17  0.00 %  0.78 %  0.00 %
90  2022-01-18  0.00 %  0.73 %  0.00 %
91  2022-01-19  0.00 %  0.70 %  0.00 %

[92 rows x 4 columns]